controller_list:
  - name: fake_arm_robot_controller
    joints:
      - base_link__link_01
      - link_01__link_02
      - link_02__link_03
      - link_03__link_04
      - link_04__gripper
  - name: fake_gripper_controller
    joints:
      - gripper__gripper_left
      - gripper__gripper_right